name: Publish NuGet Package to GitHub Packages

on:
  push:
    branches:
      - main  # Adjust this according to your branch name
  workflow_dispatch:  # Manually trigger workflow from Actions tab

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'  # Specify the .NET version you need

    - name: Build and publish
      run: |
        dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.token }} --source https://nuget.pkg.github.com/zumwani/index.json
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
